version: "3.4"

services:
  metrics-humidity:
    container_name: metrics-humidity
    image: flerkam/metrics-humidity:v0.1.0
    restart: unless-stopped
    ports:
      - "80"
    networks:
      - rpi
    env_file:
      - ./.env

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
    restart: unless-stopped
    depends_on:
      - metrics-humidity
    networks:
      - rpi

  grafana:
    image : grafana/grafana
    user: "${UID}:${GID}"
    depends_on:
      - prometheus
    ports:
      - "3000"
    volumes:
      - ./grafana/data/:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./.env
    networks:
      - rpi
    restart: unless-stopped
    labels:
      - "traefik.http.routers.grafanaproxy.rule=Host(`grafana.ubuntu`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

networks:
  rpi:
     external: true